version: "3.8"

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - bimabazaar

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./logs:/var/log/bimabazaar
    command: -config.file=/etc/promtail/config.yml
    networks:
      - bimabazaar
    depends_on:
      - loki

networks:
  bimabazaar:
